name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a recent LTS version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Debug dependencies
        run: npm list react-scripts || echo "react-scripts not found"
     
      - name: Build application
        run: npm run build
